### ISSUE TITLE
Refactoring out DaCapo hacks into the DaCapo class

### ISSUE THREAD

**Issue by caizixian** [anupli/running-ng#111]
When running DaCapo with callbacks (by overriding the `callback` of an instance of `DaCapo`), it uses `-cp` instead of `-jar` to run DaCapo, which bypasses the MANIFEST file in the jar, causing issues like below

```
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.dacapo.harness.Cassandra.prepare(Cassandra.java:124)
    at org.dacapo.harness.Benchmark.run(Benchmark.java:205)
    at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:225)
    at org.dacapo.harness.TestHarness.main(TestHarness.java:170)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at Harness.main(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
    at org.apache.cassandra.config.DatabaseDescriptor.guessFileStore(DatabaseDescriptor.java:1193)
    at org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:550)
    at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:350)
    at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:178)
    at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:162)
    at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:816)
    at org.apache.cassandra.service.EmbeddedCassandraService.start(EmbeddedCassandraService.java:49)
    ... 13 more
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: access to public member failed: jdk.internal.ref.Cleaner.clean[Ljava.lang.Object;@78fbff54/invokeVirtual, from org.apache.cassandra.io.util.FileUtils (unnamed module @158da8e)
    at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:107)
    ... 20 more
Caused by: java.lang.IllegalAccessException: access to public member failed: jdk.internal.ref.Cleaner.clean[Ljava.lang.Object;@78fbff54/invokeVirtual, from org.apache.cassandra.io.util.FileUtils (unnamed module @158da8e)
    at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:942)
    at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:2201)
    at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:2141)
    at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:2285)
    at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:2278)
    at java.base/java.lang.invoke.MethodHandles$Lookup.unreflect(MethodHandles.java:1747)
    at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:96)
```

The current workaround changes `JavaBenchmark` instead of `DaCapo`, which can be confusing for people using other Java benchmark suites. This DaCapo specific hack should be moved to `DaCapo`

https://github.com/anupli/running-ng/blob/4a8a9a027aaf93acc03b3960eb3b9eb470dd222c/src/running/benchmark.py#L208

This DaCapo specific hack should be moved to `DaCapo`, and be conditional on whether `-jar` is used.

https://github.com/anupli/running-ng/blob/4a8a9a027aaf93acc03b3960eb3b9eb470dd222c/src/running/suite.py#L182

Code comment and documentation need to be added.

**Comment by caizixian** [comment]
https://mmtk.zulipchat.com/#narrow/stream/262677-ANU-Research/topic/Using.20new.20dacapo/near/270150954
