### ISSUE TITLE
Return code is 0 for ValueError

### ISSUE THREAD

**Issue by qinsoon** [anupli/running-ng#120]
For example, with the following error, we should expect `running` to return a non-zero value. When we use running for CI, a zero return value is considered as pass, and can easily be neglected unless we look into the logs.
```console
Run id: linux-x86_64-batik-fastdebug-fv-az477-706-2023-09-13-Wed-024258
Traceback (most recent call last):
  File "/home/runner/.local/bin/running", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.10/site-packages/running/__main__.py", line 48, in main
    if m.run(args):
  File "/home/runner/.local/lib/python3.10/site-packages/running/command/runbms.py", line 383, in run
    configuration.resolve_class()
  File "/home/runner/.local/lib/python3.10/site-packages/running/config.py", line [46](https://github.com/mmtk/mmtk-openjdk/actions/runs/6167075597/job/16738052124?pr=241#step:15:47), in resolve_class
    self.__items[cls_name] = load_class(
  File "/home/runner/.local/lib/python3.10/site-packages/running/config.py", line 14, in load_class
    return {k: cls.from_config(k, v) for (k, v) in config.items()}
  File "/home/runner/.local/lib/python3.10/site-packages/running/config.py", line 14, in <dictcomp>
    return {k: cls.from_config(k, v) for (k, v) in config.items()}
  File "/home/runner/.local/lib/python3.10/site-packages/running/suite.py", line [47](https://github.com/mmtk/mmtk-openjdk/actions/runs/6167075597/job/16738052124?pr=241#step:15:48), in from_config
    return BenchmarkSuite.CLS_MAPPING[config["type"]](name=name, **config)
  File "/home/runner/.local/lib/python3.10/site-packages/running/suite.py", line 109, in __init__
    raise ValueError(
ValueError: DaCapo release rc not recongized
```

**Comment by caizixian** [comment]
That's weird. A Python exception should be a non-zero exit.

**Comment by caizixian** [comment]
Can you reproduce this locally?

**Comment by caizixian** [comment]
I think the problem is with the pipe.

```console
$ false
$ echo $?
1
$ false | tee 123
$ echo $?
0
```

https://github.com/mmtk/mmtk-openjdk/actions/runs/6167075597/job/16738053692

<img width="982" alt="Screenshot 2023-09-13 at 14 16 37" src="https://github.com/anupli/running-ng/assets/2891235/18afd195-8de1-40b1-8075-f0ec71954fb5">

**Comment by caizixian** [comment]
I don't think this is a running issue. Please reopen if you disagree.
